  0 archivo(s) copiado(s)
  SDL_AA1_02.cpp
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(445): warning C4553: '==': el operador no tiene efecto; ¿ha pensado en '='?
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(30): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(30): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(35): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(35): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(40): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(40): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(44): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(44): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(47): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(47): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(51): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(51): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(64): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(64): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(69): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(69): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(78): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(78): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(88): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(88): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(90): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(90): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(145): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(145): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(159): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(159): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(172): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(172): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(201): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(201): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(220): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(220): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(448): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(448): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(450): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  c:\users\win7\desktop\repositorio\actividades-sdl-2018\actividades sln\src\aa1_02\sdl_aa1_02.cpp(450): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
  AA1_02.vcxproj -> C:\Users\Win7\Desktop\Repositorio\Actividades-SDL-2018\Actividades SLN\\bin\x64Debug\AA1_02.exe
